version: '3.7'

services:

  frontend:
    container_name: react
    build:
      context: ./frontend
      dockerfile: ./src/Dockerfile
    volumes:
      - '.:/frontend/react-typescript'
    ports:
      - "3000:3000"
    networks:
      - appnet
    depends_on:
      - backend
  backend:
    container_name: api
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL_2=Host=postgres;Port=5432;Database=${DATABASE_NAME};Username=${DATABASE_USERNAME};Password=${DATABASE_PASSWORD}
    networks:
      - appnet
    depends_on:
      - postgres

  postgres:
    image: postgres:18
    container_name: postgres_react
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/18/docker
    networks:
      - appnet
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USERNAME} -d ${DATABASE_NAME} || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 5s

networks:
  appnet:
    driver: bridge

volumes:
  pgdata:
